[workspace]
members = [
    "agpm_abstract",
    "agpm_pm",
    "agpm_dirs",
    "agpm_store",
    "agpm_interactions",
    "agpm_lib",
    "agpm",
    "tests"
]

[workspace.package]
license = "Unlicense OR CC0-1.0 OR MIT"
repository = "https://github.com/david-soto-m/"
