[package]
name = "amisgitpm"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/david-soto-m/"
categories = ["command-line-interface", "filesystem", "development-tools", "config"]
keywords = ["Git", "Package management", "building", "testing", "development"]
description = "A package manager for git repos"

[dependencies]

# Main dep
git2 = "^0.15"

# Serialization
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"

# Paralelization and async
rayon = "^1.5" #paralel computing

# UI
clap = { version = "^4", features = ["derive"] } # arguments
dialoguer = "^0.10" # general cli utils

# Utils
directories = "^4.0" # config and local and stuff
json_tables = "^0.0" # table management
regex = "^1.6"
glob = "0.3.0"
markdown-extract = "^2.0"
subprocess = "^0.2"
prettytable-rs = {version = "^0.9", default-features = false}
fs_extra = "^1.2"


[build-dependencies]
directories = "^4.0" # config and local and stuff
