[package]
name = "amisgitpm"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/david-soto-m/"
categories = ["command-line-interface", "filesystem", "development-tools", "config"]
keywords = ["Git", "Package management", "building", "testing", "development"]
description = "A package manager for git repos"

[dependencies]

# Main dep
git2 = "^0.14"

# Serialization
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"
markdown = "^0.3"

# Paralelization and async
rayon = "^1.5" #paralel computing
tokio = {version = "1", features = ["full"]}
# To be refined to the features that are eventually used.
# Probably sync and rt and rt-multi-thread, maybe also File, and io
tokio-test = "^0.4" # testing

# UI
clap = { version = "^3.2", features = ["derive"] } # arguments
indicatif = "^0.16" # progress bars
console = "^0.15" # color
dialoguer = "^0.10" # general cli utils

# Utils
directories = "^4.0" # config and local and stuff
json_tables = "^0.0.2" # table management
regex = "^1.6"


[build-dependencies]
directories = "^4.0" # config and local and stuff
