[package]
name = "amisgitpm"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/david-soto-m/"
categories = ["command-line-interface", "filesystem", "development-tools", "config"]
keywords = ["Git", "Package management", "building", "testing", "development"]
description = "A package manager for git repos"

[dependencies]

git2 = "^0.14"

serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"

futures = "^0.3"
tokio = {version = "1", features = ["full"]}
# To be refined to the features that are eventually used.
#Probably sync and rt and rt-multi-thread, maybe also File, and io
tokio-test = "^0.4"
rayon = "^1.5" #paralel computing

directories = "^4.0" # config and local and stuff
clap = { version = "^3.2", features = ["derive"] } # arguments
indicatif = "^0.16" # progress bars
console = "^0.15" #color
dialoguer = "^0.10" # general cli utils


json_tables = "^0.0.1" # table management
