[package]
name = "agpm_interactions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agpm_abstract = {path = "../agpm_abstract"}
thiserror = "^1.0"
dialoguer = "^0.10" # general cli utils
console = "0.15.2"
fs_extra = "^1.2"
prettytable-rs = {version = "^0.9", default-features = false}
git2 = "^0.15"
serde_json = "^1.0"
